version: '3'

services:

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - app.env

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    env_file:
      - web.env
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    env_file:
      - omgwtfssl.env
    networks:
      - proxy-tier

volumes:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
