version: '3'

services:

  app:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - config:/usr/src/nextcloud/config
      - ./data:/usr/src/nextcloud/data
      - ./custom_apps:/usr/src/nextcloud/custom_apps
    env_file:
      - app.env

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    env_file:
      - web.env
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

volumes:
  nextcloud:
  certs:
  vhost.d:
  html:
  config:

networks:
  proxy-tier:
