version: '3'

services:

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - db.env
    environment:
      - POSTGRES_HOST=localhost

  adminer:
    image: adminer
    restart: always
    ports:
      - 8585:8080
    depends_on:
      - db

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redisdata:/data

  app:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/usr/src/nextcloud/config
      - ./data:/usr/src/nextcloud/data
      - ./custom_apps:/usr/src/nextcloud/custom_apps
    env_file:
      - app.env
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - .ssl:/etc/ssl/nginx
      - ./nginx.conf.template:/etc/nginx/conf.d/mysite.template
    env_file:
      - web.env
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - app
    networks:
      - web
      - default


volumes:
  nextcloud:
  vhost.d:
  html:
  config:

networks:
  web:
    external: true
