version: '3'

services:

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - db.env
    environment:
      - POSTGRES_HOST=localhost

  app:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/usr/src/nextcloud/config
      - ./data:/usr/src/nextcloud/data
      - ./custom_apps:/usr/src/nextcloud/custom_apps
    env_file:
      - app.env
    depends_on:
      - db

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - .ssl:/etc/ssl/nginx
      - ./nginx.conf.template:/etc/nginx/conf.d/mysite.template
    env_file:
      - web.env
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../ssl:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    env_file:
      - proxy.env

volumes:
  nextcloud:
  vhost.d:
  html:
  config:

networks:
  proxy-tier:
