version: '3'

services:

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
    environment:
      - POSTGRES_HOST=localhost

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - config:/usr/src/nextcloud/config
    env_file:
      - app.env
    environment:
      - POSTGRES_HOST=db
      - VIRTUAL_HOST=nextcloud.local
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    env_file:
      - web.env
    environment:
      - VIRTUAL_HOST=nextcloud.local
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=nextcloud.local
      - CA_SUBJECT=nextcloud.local
      - SSL_KEY=/certs/nextcloud.local.key
      - SSL_CSR=/certs/nextcloud.local.csr
      - SSL_CERT=/certs/nextcloud.local.crt
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:
  config:

networks:
  proxy-tier:
